$store_id = 971;

$adult_verbiage = <<<HTML

            <h4 style="color:white;">Epic Axe Throwing &amp; Social House<br />Accident Waiver and Release of Liability Agreement</h3>
            <h3 style="color:white;">(This is an important legal document: Read carefully before signing)</h3>
            <br />
            <p>I HEREBY ASSUME ALL OF THE RISKS OF PARTICIPATING IN ANY/ALL ACTIVITIES ASSOCIATED WITH THIS EVENT, including by way of example and not limitation, any risks that may arise from negligence or carelessness on the part of the persons or entities being released, from dangerous or defective equipment or property owned, maintained, or controlled by them, or because of their possible liability without fault.</p>
            <p>I certify that I am physically fit, have sufficiently prepared or trained for participation in this activity, and have not been advised to not participate by a qualified medical professional. I certify that there are no health-related reasons or problems which preclude my participation in this activity. I acknowledge that this Accident Waiver and Release of Liability Form will be used by the event holders, sponsors, and organizers of the activity in which I may participate, and that it will govern my actions and responsibilities at said activity. In consideration of my application and permitting me to participate in this activity, I hereby take action for myself, my executors, administrators, heirs, next of kin, successors, and assigns as follows:</p>
            <p>(A) I WAIVE, RELEASE, AND DISCHARGE from any and all liability, including but not limited to, liability arising from the negligence or fault of the entities or persons released, for my death, disability, personal injury, property damage, property theft, or actions of any kind which may hereafter occur to me including my traveling to and from this activity, THE FOLLOWING ENTITIES OR PERSONS: Epic Axe Throwing and Social House LLC. and/or their directors, officers, employees, volunteers, representatives, and agents, and the activity holders, sponsors, and property owners.</p>
            <p>(B) INDEMNIFY, HOLD HARMLESS, AND PROMISE NOT TO SUE the entities or persons mentioned in this paragraph from any and all liabilities or claims made as a result of participation in this activity, whether caused by the negligence of release or otherwise.</p>
            <p>I acknowledge that Epic Axe Throwing and Social House LLC and their directors, officers, volunteers, representatives, and agents are NOT responsible for the errors, omissions, acts, or failures to act of any party or entity conducting a specific activity on their behalf.</p>            <p>I acknowledge that this activity may involve a test of a person's physical and mental limits and carries with it the potential for death, severe injury, and property loss. The risks include, but are not limited to, those caused by terrain, facilities, temperature, weather, condition of participants, equipment, vehicular traffic, lack of hydration, and actions of other people including, but not limited to, participants, volunteers, monitors, and/or producers of the activity. These risks are not only inherent to participants, but are also present for volunteers.</p>
            <p>I hereby consent to receive medical treatment which may be deemed advisable in the event of injury, accident, and/or illness during this activity. I understand that while participating in this activity, I may be photographed. I agree to allow my photo, video, or film likeness to be used for any legitimate purpose by the activity holders, producers, sponsors, organizers, and assigns.</p>
            <p>The Accident Waiver and Release of Liability Form shall be construed broadly to provide a release and waiver to the maximum extent permissible under applicable law.</p>
            <p>I CERTIFY THAT I HAVE READ THIS DOCUMENT AND I FULLY UNDERSTAND ITS CONTENT. I AM AWARE THAT THIS IS A RELEASE OF LIABILITY AND A CONTRACT AND I SIGN IT OF MY OWN FREE WILL.</p>
HTML;

$adult_consent = <<<HTML
By checking here, you acknowledge you have read and understand the above terms, and are consenting to the use of your electronic signature in lieu of an original signature on paper. You have the right to request that you sign a paper copy instead. By checking here, you are waiving that right. After consent, you may, upon written request to us, obtain a paper copy of an electronic record. No fee will be charged for such copy and no special hardware or software is required to view it. Your agreement to use an electronic signature with us for any documents will continue until such time as you notify us in writing that you no longer wish to use an electronic signature. There is no penalty for withdrawing your consent. You should always make sure that we have a current email address in order to contact you regarding any changes, if necessary.
HTML;

$adult_optin = <<<HTML
By opting in with your email address, you agree to join our newsletter, so we may stay in contact with you and notify you of upcoming events at Epic Axe Throwing and Social House.
HTML;

// (same verbiage as adult)
$minor_verbiage = <<<HTML

            <h4 style="color:white;">Epic Axe Throwing &amp; Social House<br />Accident Waiver and Release of Liability Agreement</h3>
            <h3 style="color:white;">(This is an important legal document: Read carefully before signing)</h3>
            <br />
            <p>I HEREBY ASSUME ALL OF THE RISKS OF PARTICIPATING IN ANY/ALL ACTIVITIES ASSOCIATED WITH THIS EVENT, including by way of example and not limitation, any risks that may arise from negligence or carelessness on the part of the persons or entities being released, from dangerous or defective equipment or property owned, maintained, or controlled by them, or because of their possible liability without fault.</p>
            <p>I certify that I am physically fit, have sufficiently prepared or trained for participation in this activity, and have not been advised to not participate by a qualified medical professional. I certify that there are no health-related reasons or problems which preclude my participation in this activity. I acknowledge that this Accident Waiver and Release of Liability Form will be used by the event holders, sponsors, and organizers of the activity in which I may participate, and that it will govern my actions and responsibilities at said activity. In consideration of my application and permitting me to participate in this activity, I hereby take action for myself, my executors, administrators, heirs, next of kin, successors, and assigns as follows:</p>
            <p>(A) I WAIVE, RELEASE, AND DISCHARGE from any and all liability, including but not limited to, liability arising from the negligence or fault of the entities or persons released, for my death, disability, personal injury, property damage, property theft, or actions of any kind which may hereafter occur to me including my traveling to and from this activity, THE FOLLOWING ENTITIES OR PERSONS: Epic Axe Throwing and Social House LLC. and/or their directors, officers, employees, volunteers, representatives, and agents, and the activity holders, sponsors, and property owners.</p>
            <p>(B) INDEMNIFY, HOLD HARMLESS, AND PROMISE NOT TO SUE the entities or persons mentioned in this paragraph from any and all liabilities or claims made as a result of participation in this activity, whether caused by the negligence of release or otherwise.</p>
            <p>I acknowledge that Epic Axe Throwing and Social House LLC and their directors, officers, volunteers, representatives, and agents are NOT responsible for the errors, omissions, acts, or failures to act of any party or entity conducting a specific activity on their behalf.</p>            <p>I acknowledge that this activity may involve a test of a person's physical and mental limits and carries with it the potential for death, severe injury, and property loss. The risks include, but are not limited to, those caused by terrain, facilities, temperature, weather, condition of participants, equipment, vehicular traffic, lack of hydration, and actions of other people including, but not limited to, participants, volunteers, monitors, and/or producers of the activity. These risks are not only inherent to participants, but are also present for volunteers.</p>
            <p>I hereby consent to receive medical treatment which may be deemed advisable in the event of injury, accident, and/or illness during this activity. I understand that while participating in this activity, I may be photographed. I agree to allow my photo, video, or film likeness to be used for any legitimate purpose by the activity holders, producers, sponsors, organizers, and assigns.</p>
            <p>The Accident Waiver and Release of Liability Form shall be construed broadly to provide a release and waiver to the maximum extent permissible under applicable law.</p>
            <p>I CERTIFY THAT I HAVE READ THIS DOCUMENT AND I FULLY UNDERSTAND ITS CONTENT. I AM AWARE THAT THIS IS A RELEASE OF LIABILITY AND A CONTRACT AND I SIGN IT OF MY OWN FREE WILL.</p>
HTML;

$minor_consent = <<<HTML
Acknowledgement of Understanding: I, the PARENT OR GUARDIAN, affirm that I have explained the activity risks and the safety rules to my minor child and that the minor child understands both the risks and rules of participating in this event. I have read the assumption of risks, waiver of liability, and indemnification agreements stated in the Accident Waiver and Release of Liability Agreement and fully understand its terms extend to my minor child. I understand that I am giving up substantial rights for myself and my minor child, including the right to sue on my behalf or the behalf of my minor child. I further acknowledge that I am signing this agreement freely and voluntarily and intend my signature to be a complete and unconditional release of all liability, including that due to ordinary negligence by Epic Axe and Social House, to the greatest extent allowed by law of the State of North Carolina.
HTML;
